- hosts: localhost
  vars_files:
  - credentials.yml
  tasks:
  - name: launch linux os in aws
    ec2:
        key_name: "aws-os-test1"
        instance_type: "t2.micro"
        image: "ami-0ebc1ac48dfd14136"
        wait: yes
        count: 1
        vpc_subnet_id: "subnet-52cff53a"
        assign_public_ip: yes
        region: "ap-south-1"
        state: present
        group_id: "sg-06c4ced03ae7ca57b"
        aws_access_key: "{{ username }}"
        aws_secret_key: "{{ userpass }}"
    register: ec2
  - name: adding group for dynamic login to ec2 instance
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: ec2_machine
    with_items: "{{ ec2.instances }}"
  - name: wait for SSH 
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state:  started
    with_items: "{{ ec2.instances }}"
- hosts: ec2_machine
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: "/root/ansible_task2/aws-os-test1.pem"
  tasks:
  - name: install httpd
    command: "yum install httpd -y"
  - copy:
      content: "Webpage launched successfully\n"
      dest: "/var/www/html/index.html"
  - service:
      name: "httpd"
      state: started

